<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lego II - Diferença-em-diferenças</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
<meta name="twitter:title" content="Lego II - Diferença-em-diferenças">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="topico6_files/figure-html/unnamed-chunk-4-1.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Lego II</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../template.html" rel="" target="">
 <span class="menu-text">Template</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tópicos" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Tópicos</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tópicos">    
        <li>
    <a class="dropdown-item" href="../topicos/topico1.html" rel="" target="">
 <span class="dropdown-text">Simulações</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../topicos/topico2.html" rel="" target="">
 <span class="dropdown-text">Regressão linear simples</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../topicos/topico3.html" rel="" target="">
 <span class="dropdown-text">Regressão linear múltipla</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../topicos/topico4.html" rel="" target="">
 <span class="dropdown-text">Experimentos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../topicos/topico5.html" rel="" target="">
 <span class="dropdown-text">Regressão descontínua</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../topicos/topico6.html" rel="" target="">
 <span class="dropdown-text">Diferença-em-diferenças</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-replicações" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Replicações</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-replicações">    
        <li>
    <a class="dropdown-item" href="../replicacao/replicacao1.html" rel="" target="">
 <span class="dropdown-text">Replicação I</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../replicacao/replicacao2.html" rel="" target="">
 <span class="dropdown-text">Replicação II</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../replicacao/replicacao3.html" rel="" target="">
 <span class="dropdown-text">Replicação III</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="http://www.github.com/meirelesff" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução">Introdução</a></li>
  <li><a href="#did-com-interações" id="toc-did-com-interações" class="nav-link" data-scroll-target="#did-com-interações">DiD com interações</a>
  <ul class="collapse">
  <li><a href="#contexto-e-dados" id="toc-contexto-e-dados" class="nav-link" data-scroll-target="#contexto-e-dados">Contexto e dados</a></li>
  <li><a href="#visualização-das-trajetórias" id="toc-visualização-das-trajetórias" class="nav-link" data-scroll-target="#visualização-das-trajetórias">Visualização das trajetórias</a></li>
  <li><a href="#estimação" id="toc-estimação" class="nav-link" data-scroll-target="#estimação">Estimação</a></li>
  <li><a href="#inferência" id="toc-inferência" class="nav-link" data-scroll-target="#inferência">Inferência</a></li>
  </ul></li>
  <li><a href="#did-com-efeitos-fixos" id="toc-did-com-efeitos-fixos" class="nav-link" data-scroll-target="#did-com-efeitos-fixos">DiD com efeitos-fixos</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Diferença-em-diferenças</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introdução" class="level2">
<h2 class="anchored" data-anchor-id="introdução">Introdução</h2>
<p>Estas notas introduzem a implementação em <code>R</code> da última estratégia de identificação que vimos no curso: diferença-em-diferenças, ou <em>DiD</em>. Como vimos em aula, a ideia básica aqui é compararmos a trajetória de uma variável de interesse entre dois grupos, um de tratamento e outro de controle, antes e depois da aplicação do tratamento – que pode ser uma política pública, uma mudança institucional, um desastre natural, enfim, algo que afete apenas as unidades no grupo de tratamento. Dessa forma, a diferença da diferença entre os dois grupos antes e depois do evento será a nossa estimativa do efeito causal do tratamento sobre os tratados (o <em>average treatment effect on the treated</em>, ou <em>ATT</em>). Em outras palavras, <em>DiD</em> é uma forma de explorarmos interrupções em tendências plausivelmente similares ou paralelas.</p>
<p>Veremos duas formas de especificar modelos <em>DiD</em>: a tradicional, usando interações para um <em>setup</em> básico com dois grupos e dois períodos; e outra mais flexível, usando efeitos-fixos para grupos e períodos (algo popularmente conhecido como <em>two-way fixed effects</em>, ou <em>TWFE</em>). A primeira é mais simples e intuitiva, mas a segunda é comum em pesquisas aplicadas.</p>
<p>Para seguir estas notas, precisaremos carregar alguns pacotes já conhecidos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary) <span class="co"># Para exportar tabelas de regressão</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)    <span class="co"># Para várias tarefas</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest)       <span class="co"># Para estimar modelos de regressão</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Também precisaremos de alguns dados. Especificamente, usaremos os de <span class="citation" data-cites="card1993minimum">Card e Krueger (<a href="#ref-card1993minimum" role="doc-biblioref">1993</a>)</span>, que exploram a introdução de um aumento de salários mínimos em New Jersey, de 4,25 para 5,05 dólares por hora de trabalho, para ver o seu impacto sobre o número de empregos no setor de <em>fast food</em>. Esses dados estão disponíveis <a href="../docs/data/ck.Rda">neste link</a> e podem ser carregados com:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"ck.Rda"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="did-com-interações" class="level2">
<h2 class="anchored" data-anchor-id="did-com-interações">DiD com interações</h2>
<section id="contexto-e-dados" class="level3">
<h3 class="anchored" data-anchor-id="contexto-e-dados">Contexto e dados</h3>
<p>O estudo de <span class="citation" data-cites="card1993minimum">Card e Krueger (<a href="#ref-card1993minimum" role="doc-biblioref">1993</a>)</span> é um exemplo clássico de <em>DiD</em>. O <em>paper</em> explora o aumento de salários mínimos em New Jersey para ver seu impacto sobre emprego – particularmente, para examinar se aumento do salário mínimo causa queda na taxa de emprego. Os dados do estudo vêm de 410 restaurantes entrevistados (i.e., nossas unidades) em New Jersey e na Pensilvânia (i.e., grupos de tratamento e controle, respectivamente), coletados em 1991 e 1992 via <em>survey</em> telefônico, antes e depois da implementação do aumento do salário mínimo em New Jersey. A variável de interesse é o número de empregados em regime <em>full time</em> em cada restaurante, indicada por <code>employment</code> na base, e o tratamento é a introdução de um aumento de salários mínimos em New Jersey em abril de 1992. A variável <code>treat</code> indica se um dado restaurante <span class="math inline">\(i\)</span> está em New Jersey (<code>treat == 1</code>) ou na Pensilvânia (<code>treat == 0</code>), e a variável <code>period</code> indica se a observação é de 1992 (<code>period == 1</code>) ou de 1991 (<code>period == 0</code>). Podemos ver a estrutura da base com:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ck)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  company_id period treat    bk   kfc wendys employment
       &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
1          1      0     0     1     0      0       40.5
2          1      1     0     1     0      0       24  
3          2      0     0     0     1      0       13.8
4          2      1     0     0     1      0       11.5
5          3      0     0     0     1      0        8.5
6          3      1     0     0     1      0       10.5</code></pre>
</div>
</div>
</section>
<section id="visualização-das-trajetórias" class="level3">
<h3 class="anchored" data-anchor-id="visualização-das-trajetórias">Visualização das trajetórias</h3>
<p>Antes de estimar um modelo, podemos fazer o exercício mais intuitivo possível para ver se parece haver algum efeito decorrente do aumento do salário mínimo: plotar a média empregos para os dois grupos, antes e depois. Usando o <code>ggplot2</code>, podemos fazer isso assim<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ck <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(treat, period) <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">employment =</span> <span class="fu">mean</span>(employment, <span class="at">na.rm =</span> T)) <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> period, <span class="at">y =</span> employment, <span class="at">color =</span> <span class="fu">factor</span>(treat))) <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Período"</span>, <span class="at">y =</span> <span class="st">"Empregos"</span>, <span class="at">color =</span> <span class="st">"Tratamento"</span>) <span class="sc">+</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">25</span>) <span class="co"># Trava o eixo Y</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'treat'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="topico6_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>É curioso notar que, se qualquer coisa, o número de empregos caiu na Pensilvânia e aumentou em New Jersey, mas, como <span class="citation" data-cites="card1993minimum">Card e Krueger (<a href="#ref-card1993minimum" role="doc-biblioref">1993</a>)</span> notam, o período era de recessão nos Estados Unidos e a diferença de trajetória não é tão saliente em termos de magnitude. Em termos de médias, a diferença antes e depois de cada grupo é a seguinte:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ck <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(treat, period) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">employment =</span> <span class="fu">mean</span>(employment, <span class="at">na.rm =</span> T))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'treat'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   treat [2]
  treat period employment
  &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
1     0      0       23.3
2     0      1       21.2
3     1      0       20.4
4     1      1       21.0</code></pre>
</div>
</div>
<p>Enquanto que na Pensilvânia a média de empregos caiu cerca de 2.1, em New Jersey subi 0.6. Com esses números, podemos adicionar ao gráfico anterior uma linha que indica a trajetória contrafactual de New Jersey:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>ck <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(treat, period) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">employment =</span> <span class="fu">mean</span>(employment, <span class="at">na.rm =</span> T)) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> period, <span class="at">y =</span> employment, <span class="at">color =</span> <span class="fu">factor</span>(treat))) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Linha tracejada para a trajetória contrafactual de New Jersey</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">xend =</span> <span class="dv">1</span>, <span class="at">y =</span> <span class="fl">20.4</span>, <span class="at">yend =</span> <span class="fl">19.3</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Período"</span>, <span class="at">y =</span> <span class="st">"Empregos"</span>, <span class="at">color =</span> <span class="st">"Tratamento"</span>) <span class="sc">+</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">25</span>) <span class="co"># Trava o eixo Y</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'treat'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="topico6_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="estimação" class="level3">
<h3 class="anchored" data-anchor-id="estimação">Estimação</h3>
<p>Conforme vimos em aula, o truque do DiD de dois períodos, dois grupos e um tratamento está no termo interativo, ou multiplicativo, entre o indicador de tratamento e o indicador de período. A equação geral desse tipo de especificação da estratégia é:</p>
<p><span class="math display">\[
Emprego_{it} = \beta_0 + \beta_1 \text{treat}_i + \beta_2 t + \beta_3 (\text{treat}_i \times t) + \epsilon_{it}
\]</span></p>
<p>onde <span class="math inline">\(i\)</span> indexa cada um dos 410 restaurantes, <span class="math inline">\(t \in \{0, 1\}\)</span> indica e indexa os dois períodos<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>; com o modelo estimado, <span class="math inline">\(\hat{\beta_3}\)</span> é o nosso estimador do <em>ATT</em>, indicando o quanto o grupo tratado variou a mais ou a menos do que a tendência seguida pelo grupo de controle. Para estimar esse modelo, podemos usar o <code>lm</code> do <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(employment <span class="sc">~</span> treat <span class="sc">+</span> period <span class="sc">+</span> treat<span class="sc">:</span>period, <span class="at">data =</span> ck)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Explicação da sintaxe: para além das variáveis <code>treat</code> e <code>period</code>, usamos <code>treat:period</code> para fazer a interação, ou multiplicação, dos dois indicadores. Alternativamente, poderíamos escrever <code>treat * period</code>, que é uma forma mais curta de escrever a mesma coisa. O <code>lm</code> também nos dá um resumo do modelo, que podemos ver com:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = employment ~ treat + period + treat:period, data = ck)

Residuals:
    Min      1Q  Median      3Q     Max 
-21.166  -6.439  -1.027   4.473  64.561 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    23.331      1.072  21.767   &lt;2e-16 ***
treat          -2.892      1.194  -2.423   0.0156 *  
period         -2.166      1.516  -1.429   0.1535    
treat:period    2.754      1.688   1.631   0.1033    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.406 on 790 degrees of freedom
  (26 observations deleted due to missingness)
Multiple R-squared:  0.007401,  Adjusted R-squared:  0.003632 
F-statistic: 1.964 on 3 and 790 DF,  p-value: 0.118</code></pre>
</div>
</div>
<p>As estimativas recuperam as médias que calculamos antes. A constante de 23.33 é exatamente a média do número de empregos em restaurantes da Pensilvânia em 1991, e o coeficiente de <code>treat</code> é a diferença entre as médias de New Jersey e Pensilvânia em 1991, -2.89 – o que, somado a <span class="math inline">\(\hat{\beta_0}\)</span>, indica que a média de empregos em New Jersey era de 20.439. Quando <code>period==1</code> e <code>treat==0</code>, isto é, quando olhamos para a Pensilvânia depois do tratamento, a média de empregos cai para 21.165, i.e., <span class="math inline">\(\hat{beta_0} + \hat{\beta_2}\)</span>; finalmente, quando <code>period==1</code> e <code>treat==1</code>, a média de empregos em New Jersey sobe para 21.027, i.e., <span class="math inline">\(\hat{\beta_0} + \hat{\beta_1} + \hat{\beta_2} + \hat{\beta_3}\)</span>. Dito de outra maneira, <span class="math inline">\(\hat{\beta_3}\)</span> é a estimativa de quanto New Jersey variou em relação à Pensilvânia depois do tratamento – pressupondo que, ausente o aumento de salário mínimo, ambos os estados terial seguido uma trajetória similar no número médio de empregos por restaurante.</p>
</section>
<section id="inferência" class="level3">
<h3 class="anchored" data-anchor-id="inferência">Inferência</h3>
<p>Em aplicações de DiD, inferência é feita usando erros-padrão que levem em conta o fato de que temos múltiplas observações de uma mesma unidade – e que, portanto, tem resíduos correlacionados. O <code>R</code> não tem uma função pronta para isso, mas podemos usar o pacote <code>fixest</code> para estimar o modelo com erros-padrão robustos a heterocedasticidade ou com <em>cluster</em>. O mesmo modelo anterior, estimado agora por meio da função <code>feols</code> do pacote <code>fixest</code>, fica assim:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>modelo_ro <span class="ot">&lt;-</span> <span class="fu">feols</span>(employment <span class="sc">~</span> treat <span class="sc">+</span> period <span class="sc">+</span> treat<span class="sc">:</span>period, <span class="at">vcov =</span> <span class="st">"hetero"</span>, <span class="at">data =</span> ck)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>NOTE: 26 observations removed because of NA values (LHS: 26).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_ro)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: employment
Observations: 794 
Standard-errors: Heteroskedasticity-robust 
             Estimate Std. Error  t value  Pr(&gt;|t|)    
(Intercept)  23.33117    1.34574 17.33705 &lt; 2.2e-16 ***
treat        -2.89176    1.43870 -2.00999  0.044772 *  
period       -2.16558    1.64121 -1.31950  0.187383    
treat:period  2.75361    1.79545  1.53366  0.125514    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 9.3819   Adj. R2: 0.003632</code></pre>
</div>
</div>
<p>Boa parte do código é igual ao que usamos com <code>lm</code>, mas, usando o argumento <code>vcov = "hetero"</code> (sim, é esquisito) indicamos que queremos erros-padrão robustos a heterocedasticidade. Para indicar que queremos erros por <em>cluster</em>, podemos usar o argumento <code>cluster</code>, especificando qual variável contém a indicação das unidades:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>modelo_cl <span class="ot">&lt;-</span> <span class="fu">feols</span>(employment <span class="sc">~</span> treat <span class="sc">+</span> period <span class="sc">+</span> treat<span class="sc">:</span>period, <span class="at">cluster =</span> <span class="sc">~</span>company_id, <span class="at">data =</span> ck)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>NOTE: 26 observations removed because of NA values (LHS: 26).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_cl)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: employment
Observations: 794 
Standard-errors: Clustered (company_id) 
             Estimate Std. Error  t value  Pr(&gt;|t|)    
(Intercept)  23.33117    1.34654 17.32681 &lt; 2.2e-16 ***
treat        -2.89176    1.43955 -2.00880  0.045215 *  
period       -2.16558    1.21802 -1.77795  0.076155 .  
treat:period  2.75361    1.30661  2.10745  0.035687 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 9.3819   Adj. R2: 0.003632</code></pre>
</div>
</div>
<p>Podemos fazer uma tabela para comparar todos os três modelos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>lista_modelos <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"Erros iid"</span> <span class="ot">=</span> modelo, </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Erros robustos"</span> <span class="ot">=</span> modelo_ro,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Erros com cluster"</span> <span class="ot">=</span> modelo_cl)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(lista_modelos, <span class="at">output =</span> <span class="st">"markdown"</span>, <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">gof_map =</span> <span class="st">"nobs"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Estimativas </caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Erros iid</th>
<th style="text-align: right;">Erros robustos</th>
<th style="text-align: right;">Erros com cluster</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">23.331</td>
<td style="text-align: right;">23.331</td>
<td style="text-align: right;">23.331</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(1.072)</td>
<td style="text-align: right;">(1.346)</td>
<td style="text-align: right;">(1.347)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">treat</td>
<td style="text-align: right;">-2.892</td>
<td style="text-align: right;">-2.892</td>
<td style="text-align: right;">-2.892</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(1.194)</td>
<td style="text-align: right;">(1.439)</td>
<td style="text-align: right;">(1.440)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">period</td>
<td style="text-align: right;">-2.166</td>
<td style="text-align: right;">-2.166</td>
<td style="text-align: right;">-2.166</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(1.516)</td>
<td style="text-align: right;">(1.641)</td>
<td style="text-align: right;">(1.218)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">treat × period</td>
<td style="text-align: right;">2.754</td>
<td style="text-align: right;">2.754</td>
<td style="text-align: right;">2.754</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(1.688)</td>
<td style="text-align: right;">(1.795)</td>
<td style="text-align: right;">(1.307)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">:—————</td>
<td style="text-align: right;">———-:</td>
<td style="text-align: right;">—————:</td>
<td style="text-align: right;">——————:</td>
</tr>
<tr class="even">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: right;">794</td>
<td style="text-align: right;">794</td>
<td style="text-align: right;">794</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Como é possível notar, levar em conta a estrutura de relação entre observações e a possibilidade de que erros não sejam distribuídos de forma homocedástica não afeta coeficientes, apenas erros-padrão, que tendem a ser maiores do que os erros-padrão clássicos – exceção aqui de alguns erros do modelo com <em>cluster</em>, que ficaram menores e que, dessa forma, devem ser preteridos. Seja como for, a conclusão é a mesma: o aumento de salários mínimos em New Jersey parece ter aumentado o número de empregos em restaurantes, em média, em cerca de 2.75.</p>
</section>
</section>
<section id="did-com-efeitos-fixos" class="level2">
<h2 class="anchored" data-anchor-id="did-com-efeitos-fixos">DiD com efeitos-fixos</h2>
<p>Nessa parte, veremos como estimar modelos <em>DiD</em> usando efeitos-fixos para grupos e períodos, especificação que é mais flexível e que permite, inclusive, que tenhamos múltiplos grupos tratados ou de controle, bem como múltiplos períodos pré e pós-tratamento. A principal mudança de especificação do modelo – que não altera estimativas que obteremos com os dados de <span class="citation" data-cites="card1993minimum">Card e Krueger (<a href="#ref-card1993minimum" role="doc-biblioref">1993</a>)</span> – é que, no lugar de incluirmos explicitamente os indicadores <code>treat</code> e <code>period</code>, os declararemos como efeitos-fixos na função <code>feols</code>, deixando apenas o termo interativo entre eles na fórmula passada. A equação geral desse tipo de especificação da estratégia é:</p>
<p><span class="math display">\[
Emprego_{it} = \alpha_i + \lambda_t + \beta (\text{treat}_i \times t) + \epsilon_{it}
\]</span></p>
<p>A notação, vale notar, é praticamente a mesma, mas é comum usarmos outras letras gregas pra indicar efeitos-fixos no lugar de uma constante para todas as unidades – em certo sentido, é como se cada grupo de unidades e tempo tivesse a sua própria constante. Para estimar esse modelo, podemos usar o <code>feols</code> do <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>modelo_fe <span class="ot">&lt;-</span> <span class="fu">feols</span>(employment <span class="sc">~</span> treat<span class="sc">:</span>period <span class="sc">|</span> company_id <span class="sc">+</span> period, <span class="at">data =</span> ck)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>NOTE: 26 observations removed because of NA values (LHS: 26).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_fe)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: employment
Observations: 794 
Fixed-effects: company_id: 410,  period: 2
Standard-errors: Clustered (company_id) 
             Estimate Std. Error t value Pr(&gt;|t|)    
treat:period     2.75    1.33755 2.05599 0.040418 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 4.39835     Adj. R2: 0.547121
                Within R2: 0.014639</code></pre>
</div>
</div>
<p>Com essa especificação, estamos deixando cada restaurante ter seu próprio intercept – isto é, que suas diferenças fixas em relação aos demais sejam absorvidas – e também que cada ano tenha seu próprio intercept. O que sobra é o efeito do tratamento sobre o grupo tratado, <span class="math inline">\(\hat{\beta}\)</span>. Enfim, uma tabela que compara os quatro modelos:<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>lista_modelos <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"Erros iid"</span> <span class="ot">=</span> modelo, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Erros robustos"</span> <span class="ot">=</span> modelo_ro,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Erros com cluster"</span> <span class="ot">=</span> modelo_cl,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Efeitos-fixos"</span> <span class="ot">=</span> modelo_fe)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(lista_modelos, <span class="at">output =</span> <span class="st">"markdown"</span>, <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">gof_map =</span> <span class="st">"nobs"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Estimativas finais </caption>
<colgroup>
<col style="width: 20%">
<col style="width: 14%">
<col style="width: 20%">
<col style="width: 24%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Erros iid</th>
<th style="text-align: right;">Erros robustos</th>
<th style="text-align: right;">Erros com cluster</th>
<th style="text-align: right;">Efeitos-fixos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">23.331</td>
<td style="text-align: right;">23.331</td>
<td style="text-align: right;">23.331</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(1.072)</td>
<td style="text-align: right;">(1.346)</td>
<td style="text-align: right;">(1.347)</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">treat</td>
<td style="text-align: right;">-2.892</td>
<td style="text-align: right;">-2.892</td>
<td style="text-align: right;">-2.892</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(1.194)</td>
<td style="text-align: right;">(1.439)</td>
<td style="text-align: right;">(1.440)</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">period</td>
<td style="text-align: right;">-2.166</td>
<td style="text-align: right;">-2.166</td>
<td style="text-align: right;">-2.166</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(1.516)</td>
<td style="text-align: right;">(1.641)</td>
<td style="text-align: right;">(1.218)</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">treat × period</td>
<td style="text-align: right;">2.754</td>
<td style="text-align: right;">2.754</td>
<td style="text-align: right;">2.754</td>
<td style="text-align: right;">2.750</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(1.688)</td>
<td style="text-align: right;">(1.795)</td>
<td style="text-align: right;">(1.307)</td>
<td style="text-align: right;">(1.338)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">:—————</td>
<td style="text-align: right;">———-:</td>
<td style="text-align: right;">—————:</td>
<td style="text-align: right;">——————:</td>
<td style="text-align: right;">————–:</td>
</tr>
<tr class="even">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: right;">794</td>
<td style="text-align: right;">794</td>
<td style="text-align: right;">794</td>
<td style="text-align: right;">794</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Como é possível perceber, independentemente do estimador usado, o resultado que obtemos é o mesmo.</p>



</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">Referências</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-card1993minimum" class="csl-entry" role="listitem">
Card, David, e Alan B Krueger. 1993. <span>«Minimum wages and employment: A case study of the fast food industry in New Jersey and Pennsylvania»</span>. National Bureau of Economic Research Cambridge, Mass., USA.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Notas de rodapé</h2>

<ol>
<li id="fn1"><p>Note que tivemos que usar <code>na.rm = T</code> para calcular a média da taxa de emprego, já que a variável <code>employment</code> tem alguns valores faltantes.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Usar apenas <span class="math inline">\(t\)</span> reduz um pouco a notação para o caso de termos apenas dois períodos, mas não serve para aplicações com mais de dois; para estes, precisamos especificar uma série de <em>dummies</em>, uma para cada período menos um, ou efeitos-fixos para os anos.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Por padrão, modelos com efeitos-fixos estimados com <code>feols</code> já saem com erros-padrão robustos por grupo, então não precisamos especificar isso explicitamente.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          // default icon
          link.classList.add("external");
      }
    }
});
</script>
</div> <!-- /content -->



</body></html>